using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using tms_mka_v2.Context;
using tms_mka_v2.Infrastructure;

namespace tms_mka_v2.Business_Logic.Abstract
{
    public interface ISalesOrderRepo
    {
        void save(SalesOrder dbitem, int? StatusFlow = null, string listSo = null);
        List<AdminUangJalan> FindAllSettlRegSO(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        int CountAllSettlRegSO(FilterInfo filters = null);
        int CountKasirTfReport(FilterInfo filters = null);
        string saveQueryGrMstrKontrak(string username, Context.Customer customer, String VehicleNo, decimal value);
        List<AdminUangJalan> FindAllKasirKasReport(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        Context.SalesOrder FindYgBentrok(string SONumber, int DriverId, DateTime TglMuat7);
        SalesOrder FindByKontrakCode(string number);
        List<SalesOrder> FindAllKasirKas(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        int CountAllBOBS(FilterInfo filters = null);
        int CountSoKlaim(FilterInfo filters = null);
        List<AdminUangJalan> FindAllBOBS(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        SalesOrder FindByCode(string number);
        int CountFindAllAdminUangJalanKontrakReport(FilterInfo filters = null);
        List<SalesOrder> FindAllAdminUangJalanSusulanKonsol(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        Context.SalesOrderProsesKonsolidasiItem FindByKonsolidasiId(int SalesOrderKonsolidasiId);
        List<AdminUangJalan> FindAllAdminUangJalanKontrakReport(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrderKontrak> FindAllKonfirmasiKontrak(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        void saveUangTf(AdminUangJalanUangTf dbitem);
        int CountListOrder(FilterInfo filters = null);
        List<SalesOrderKontrakListSo> FindAllPlanningBatalKontrak(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<AdminUangJalan> FindAllKasirTfReport(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAllListOrder(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAll(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAllOnCall(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAllKontrak(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAllPickUp(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAllKonsolidasi(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAllProsesKonsolidasi(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAllAdminUangJalan(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAllAdminDispatched(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        int CountKonfirmasiKontrak(FilterInfo filters = null);
        List<SalesOrder> FindAllKasir(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAllKlaim(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAllAUJReport(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<AdminUangJalan> FindAllAdminUangJalanReport(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<SalesOrder> FindAllKasirReport(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        SalesOrder FindByAUJ(int id);
        int Count(FilterInfo filters = null);
        int CountAllAdminUangJalanReport(FilterInfo filters = null);
        decimal HargaKonsolidasiPerItem(Context.SalesOrderProsesKonsolidasiItem Detail);
        List<SalesOrderKontrakListSo> FindAllKontrakListSo(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        int CountKontrak(FilterInfo filters = null);
        int CountOncall(FilterInfo filters = null);
        int CountPickup(FilterInfo filters = null);
        int CountAllAdminDispatched(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        int CountKonsolidasi(FilterInfo filters = null);
        int CountReportKonsolidasi(FilterInfo filters = null);
        int CountProsesKonsolidasi(FilterInfo filters = null);
        SalesOrder FindByPK(int id);
        SalesOrder FindByOnCall(int id);
        SalesOrder FindByKontrak(int id);
        SalesOrder FindByPickup(int id);
        SalesOrder FindByKonsolidasi(int id);
        SalesOrder FindByProsesKonsolidasi(int id);
        SalesOrderProsesKonsolidasiItem FindProsesKonsolidasiItem(int id);
        void delete(SalesOrder dbitem, int id);
        string generateCodeOnCall(DateTime valdate,int urutan);
        int getUrutanOnCAll(DateTime valdate);
        string generateCodeKontrak(int urutan, DateTime MuatDate);
        int getUrutanKontrak(DateTime valDate);
        string generatePickup(DateTime valdate,int urutan);
        int getUrutanPickup(DateTime valdate);
        string generateKonsolidasi(DateTime valdate,int urutan);
        int getUrutanKonsolidasi(DateTime valdate);
        string generateProsesKonsolidasi(DateTime valdate,int urutan);
        int getUrutanProsesKonsolidasi(DateTime valdate);
        string IsMuatDateExist(List<string> muatDate, int custId, int id = 0);
        string FindArea(int idSO);
        SalesOrder FindByOnCallCode(string number);
        List<OrderHistory> FindAllHistory(int idSo);
        Context.Rute FindRute(int id);
        decimal Harga(Context.SalesOrder dbso, Context.SalesOrderKontrakListSo currentKontrak = null);
        double GroupPerMonth(DateTime valdate);
        List<Context.OrderHistory> FindAllPlanningHistory();
        Context.OrderHistory FindMarketingHistory(int idSO);
        Context.OrderHistory FindPlanningHistory(int idSO);
        List<Context.OrderHistory> FindAllKonfirmasiHistory();
        List<Context.OrderHistory> FindAllAUJHistory();
        Context.OrderHistory FindKonfirmasiHistory(int idSO);
        string TanggalTiba(Context.SalesOrderOncall so);
        Context.DaftarHargaOnCallItem FindDH(int id);
        List<SalesOrder> FindAllAdminUangJalanKontrak(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        string saveQueryGrMstr(string username, Context.Customer customer, Context.SalesOrder dbso, decimal value);
        Context.SalesOrderKontrakTruck FindByKontrakIdAndTruckId(int SalesKontrakId, int DataTruckId);
        List<Context.OrderHistory> oh();
        List<SalesOrder> FindAllReportKonsolidasi(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        List<AdminUangJalan> FindAllTfBOBS(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        int CountAllTfBOBS(FilterInfo filters = null);
        List<AdminUangJalan> FindAllKasBOBS(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        int CountAllKasBOBS(FilterInfo filters = null);
        List<AdminUangJalan> FindAllTfBOBSReport(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        int CountAllTfBOBSReport(FilterInfo filters = null);
        List<AdminUangJalan> FindAllKasBOBSReport(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        int CountAllKasBOBSReport(FilterInfo filters = null);
        List<SalesOrderKontrakListSo> FindAllKlaimKontrak(int? skip = null, int? take = null, List<SortingInfo> sortings = null, FilterInfo filters = null);
        int CountSoKlaimKontrak(FilterInfo filters = null);
    }
}